//API 1
GET http://localhost:3000/todos/

###
//API 2
POST httP://localhost:3000/todos/
Content-Type: application/json

{
  "id": 7,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-2-22"
}
###
//API 3
PUT http://localhost:3000/todos/6/
Content-Type: application/json

{
  "dueDate": "2021-4-12"
}

###
//API 4
DELETE http://localhost:3000/todos/6/

###
//API 5
GET http://localhost:3000/agenda/?date=2021-2-22